#Deploy en produccion WDEV con rama desarrollo
Deploy_dev_Wdev:
  stage: deploy
  only: ['desarrollo']
  tags:
    - wdev # Deploy a produccion 
  before_script:
    - Mic="api_doc_develops_dev" #cambiar por el nombre del  job del microservicio
  script: 
    - echo "Prod - api_doc_develops_dev"
    - echo "*---------------------------------------------*"
    - echo $env_ftp_pass
    - pwd
    - sudo bundle exec middleman build
    - sudo cp -rp build/* /var/www/html/cubobit/developers
    - sudo cp -rp build/* /var/www/html/devcubobit/developers
    - sudo /gitlabCI/ok.sh "$Mic"
    
    #Deploy en produccion prod con rama master
Deploy_Produccio_S1:
  stage: test
  only: ['master']
  tags:
    - prod1 # Deploy a produccion 
  before_script:
    - Mic="api_doc_develops" #cambiar por el nombre del  job del microservicio
  script: 
    - echo "Prod - api_doc_develops"
    - echo "*---------------------------------------------*"
    - echo $env_ftp_pass
    - pwd
    - sudo bundle exec middleman build
    - sudo cp -rp build/* /var/www/html/cubobit/developers
    - sudo /gitlabCI/ok.sh "$Mic"
    
    #Deploy en produccion prod con rama master
Deploy_Produccio_S2:
  stage: test
  only: ['master']
  tags:
    - prod2 # Deploy a produccion 
  before_script:
    - Mic="api_doc_develops" #cambiar por el nombre del  job del microservicio
  script: 
    - echo "Prod - api_doc_develops"
    - echo "*---------------------------------------------*"
    - echo $env_ftp_pass
    - pwd
    - sudo bundle exec middleman build
    - sudo cp -rp build/* /var/www/html/cubobit/developers
    - sudo /gitlabCI/ok.sh "$Mic"
    
    #Deploy en produccion prod con rama master
Deploy_Produccio_LB:
  stage: test
  only: ['master']
  tags:
    - lbal # Deploy a produccion 
  before_script:
    - Mic="api_doc_develops" #cambiar por el nombre del  job del microservicio
  script: 
    - echo "Prod - api_doc_develops"
    - echo "*---------------------------------------------*"
    - echo $env_ftp_pass
    - pwd
    - sudo bundle exec middleman build
    - sudo cp -rp build/* /var/www/html/cubobit/developers
    - sudo /gitlabCI/ok.sh "$Mic"